---

- name: restart chrony
  service: name=chronyd state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: restart rsyslogd
  service: name=rsyslog state=restarted

- name: regenerate auditd rules
  shell: augenrules

- name: reload auditd
  service: name=auditd state=reloaded

- name: reload firewalld
  shell: firewall-cmd --reload

- name: reload postfix
  service: name=postfix state=reloaded
