---

- name: restart openntpd
  service: name=openntpd state=restarted

- name: restart sshd
  service: name=ssh state=restarted

- name: restart rsyslogd
  service: name=rsyslog state=restarted

- name: reload postfix
  service: name=postfix state=reloaded
