---

- include_tasks: packages.yml
- include_tasks: sudo.yml
- include_tasks: users.yml
- include_tasks: firewall.yml
- include_tasks: ssh.yml
- include_tasks: syslog.yml
- include_tasks: ntp.yml
- include_tasks: mail.yml
