---

- name: create users
  user: name="{{ item.name }}" comment="{{ item.gecos }}" groups="{{ item.groups }}"
  with_items:
    - "{{ users }}"

- name: remove default users
  user: name="{{ item }}" state=absent
  with_items:
    - centos

- name: install authorized keys
  authorized_key: user="{{ item.0.name }}" key="{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys
