---

- name: create users
  user: name="{{item.name}}" comment="{{item.gecos}}" password="{{item.password}}" groups="{{item.groups}}"
  with_items:
    - "{{ users }}"

- name: install authorized keys
  authorized_key: user="{{ item.0.name }}" key="{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys
