---

- name: install firewalld
  yum:
    name:
     - firewalld
     - python-firewall
    state: present

- name: start firewalld
  service: name=firewalld state=started enabled=yes

- firewalld:
    service: ssh
    permanent: true
    state: enabled
  notify: reload firewalld
