---

- name: install mail packages
  yum:
    name:
     - mailx
    state: present

- name: install mail packages
  yum:
    name:
     - postfix
    state: present
  when: postfix is defined

- name: install postfix config
  template: src=postfix/main.cf dest=/etc/postfix/main.cf mode=444
  notify: reload postfix
  when: postfix is defined
