---

- name: install EPEL
  yum:
    name:
      - epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: install common packages
  yum:
    name:
      - htop
      - net-tools
      - tcpdump
      - vim-enhanced
    state: present
