---

- name: install SELinux packages
  yum:
    name:
      - policycoreutils-python
      - setools-console
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: install SELinux packages
  yum:
    name:
      - python3-policycoreutils
      - setools-console
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: install SELinux packages
  yum:
    name:
      - setools-console
    state: present
  when: ansible_distribution == "Fedora"

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing
  when: selinux.enforcing is not defined or (selinux.enforcing is defined and selinux.enforcing)

- name: disable SELinux
  selinux:
    policy: targeted
    state: permissive
  when: selinux.enforcing is defined and not selinux.enforcing

- name: set SELinux staff_exec_content to false
  seboolean:
    name: staff_exec_content
    state: yes
    persistent: yes
  when: selinux.staff_exec_content is defined and selinux.staff_exec_content

- name: set SELinux staff_exec_content to false
  seboolean:
    name: staff_exec_content
    state: no
    persistent: yes
  when: selinux.staff_exec_content is defined and not selinux.staff_exec_content

- name: set SELinux user for managed users 
  shell: semanage login -a -s "{{item.seuser}}" -r s0-s0:c0.c1023 "{{item.name}}"
  ignore_errors: yes
  with_items:
    - "{{ users }}"
  when: selinux.users is defined and selinux.users
