---

- name: configure sshd
  template: src="ssh/sshd_config" dest="/etc/ssh/sshd_config" mode=444
  notify: restart sshd

- firewalld:
    service: ssh
    permanent: true
    state: enabled
  notify: reload firewalld
