---

- name: Install dependencies
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker CE
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - docker-ce

- name: Enable and start Docker
  service: name=docker state=started enabled=yes
